### ISSUE TITLE
AsseticExtension issue when using UrlGenerator and SymfonyBridges

### ISSUE THREAD

**Issue by cowlby** [mheap/Silex-Extensions#1]
Not sure if this is strictly a problem with just AsseticExtension or more a problem with the UrlGeneratorExtension but I'll post here first and see what you think.

When I use the extensions below, AsseticExtension throws an error:

``` php
$app = new Silex\Application();

$app->register(new Silex\Extension\UrlGeneratorExtension());

$app->register(new Silex\Extension\SymfonyBridgesExtension(), array(
    'symfony_bridges.class_path' => __DIR__.'/../vendor/symfony/src'
));

$app->register(new Silex\Extension\TwigExtension(), array(
    'twig.class_path' => __DIR__ . '/../vendor/twig/lib',
    'twig.path' => __DIR__ . '/../src/views'
));

$app['autoloader']->registerNamespace('SilexExtension', __DIR__ . '/../src');
$app->register(new AsseticExtension(), array());
```

The error is as follows:

```
Fatal error: Uncaught exception 'InvalidArgumentException' with message 'Identifier "request_context" is not defined.'
```

I've done a bit of troubleshooting and I believe the problem occurs specifically when SymfonyBridgesExtension and UrlGeneratorExtension are enabled. The problem starts on line 149 of AsseticExtension.php

``` PHP
// twig support
if(isset($app['twig'])) {
    $app['twig']->addExtension(new TwigAsseticExtension($app['assetic.factory']));
}
```

When Pimple resolves `$app['twig']`, it fires this code on line 29 of TwigExtension.php:

``` PHP
if (isset($app['symfony_bridges'])) {
    if (isset($app['url_generator'])) {
        $twig->addExtension(new TwigRoutingExtension($app['url_generator']));
    }
```

Following the rabbit hole, when Pimple resolves `$app['url_generator']`, the following code on line 26 of UrlGeneratorExtension.php fires:

``` PHP
return new UrlGenerator($app['routes'], $app['request_context']);
```

Since this code is firing outside of the context of a controller, it seems like `$app['request_context']` is not yet defined so Pimple throws up that exception.

My current fix is to just register the TwigAsseticExtension once I know the request_context is defined but there's probably a better way to go about fixing this.

**Comment by sveneisenschmidt** [comment]
Wow, nice debug trace :)

The error sees understandable, UrlGenerator needs a request context. At the time we're registering the AsseticExtension and adding the TwigExtension there is none.

I'll have a look into everything and maybe I can provide a fix. In the meantime you got any ideas?

**Comment by sveneisenschmidt** [comment]
Fixed. Thanks to @igorw

**Comment by cowlby** [comment]
Sweet! Thanks guys.
