### ISSUE TITLE
Please move libs in composer.json from required to suggest section

### ISSUE THREAD

**Issue by d00mko** [mheap/Silex-Extensions#14]
Please move libs in composer.json from required to suggest section
Something like
    "require": {
        "php": ">=5.3.0",
    },

   "suggest": {
        "kriswallsmith/assetic": ">=1.0",
        "twig/twig": ">=1.2.0",
        "doctrine/mongodb": "_",
        "predis/predis": "_",
        "mandango/mandango": "_",
        "knplabs/knp-markdown-bundle": "_",
        "embedly/embedly-php": "_",
        "fate/gravatar-php": "_"
    },

**Comment by igorw** [comment]
Ideally they would be separate service providers.

**Comment by d00mko** [comment]
...Wwhatever
But I can't use your repo 'cause my composer wanna download all requirements and stuck at that point

**Comment by robo47** [comment]
Suggest was proposed here: https://github.com/fate/Silex-Extensions/pull/11#issuecomment-4628201  too, PR is here https://github.com/fate/Silex-Extensions/pull/17
