### ISSUE TITLE
Split into multiple repos

### ISSUE THREAD

**Issue by mheap** [mheap/Silex-Extensions#26]
I want to install the Markdown extension, but to do so I have to install the entire Silex-Extension repo via Composer, then all of the repo's suggested packages (Doctrine etc). This is overkill if I just want Markdown support for an app that I plan to distribute.

Is there any chance you could split the repo into multiple repos, each with their own entry on Packagist?

**Comment by sveneisenschmidt** [comment]
Due the fact that I have currently no time to maintain alle the Silex-Extension stuff this won't happen in the near future. I think your idea is great and definitely should be done. Since some months I search for a volunteer to take over the repository.

**Comment by mheap** [comment]
I'm happy to take over maintenance of the repo if you like.

What would be the best way to proceed? Clone this repo multiple times and delete files until each contains only one extension? Or could we start fresh, with a new repo for each and author comments in the files to show contributions instead of commits?

**Comment by sveneisenschmidt** [comment]
Hit me up on jabber/gtalk.

**Comment by mheap** [comment]
All moved over, now to split into multiple repos

**Comment by gyndav** [comment]
Thanks for this move, I was wondering to suggest you that. Thanks.

**Comment by mheap** [comment]
NP. I've split the repos, but not used most of them in a project yet. If you find any issues,let me know :)

**Comment by gyndav** [comment]
Would you mind adding them individually on **Packagist** with auto  ?
