### ISSUE TITLE
Assetics + Twig

### ISSUE THREAD

**Issue by lyrixx** [mheap/Silex-Extensions#6]
How can i use : http://symfony.com/doc/current/cookbook/assetic/asset_management.html

It does not work.

You can see : https://github.com/lyrixx/Silex-Kitchen-Edition/commits/assetic

**Comment by sveneisenschmidt** [comment]
What does exactly not work? 
Any errors?

**Comment by lyrixx** [comment]
I do not want to load all my asset from the config.
So when I use, in a twig template, {% javascripts ... %} It does not add an asset collection to the asset manager.

Please see here : https://github.com/lyrixx/Silex-Kitchen-Edition/commit/32b4fbc7bde57edae9e912975b00bb77afe9d2f6#L8L49

**Comment by sveneisenschmidt** [comment]
I'll have a look. Do you have jabber/gtalk?

**Comment by lyrixx** [comment]
Yes, i sent you a message.

Thx

**Comment by tworzenieweb** [comment]
any updates about this issue? It will be great to use assetic in twig templates for silex

**Comment by cj** [comment]
Any updates on this?

**Comment by sveneisenschmidt** [comment]
unfortunately not.

**Comment by justinpfister** [comment]
i've been working with the Fate/Assetic extension too.. referencing the Kitchen-Edition setup.. that code doesn't seem to be working quite right..The asset files get created and saved.. but once you make modifications the asset arrays.. it seems to get buggy.

**Comment by sveneisenschmidt** [comment]
Maybe I'll have to rewrite it.

**Comment by justinpfister** [comment]
I found the big reason I was having problems was because I wasn't paying attention to the assetic ['debug'] behavior. It was caching the the scripts.js so of course it wasn't updating like I wanted.. However, I'm still finding that when I add additional j-scripts like jquery-extensions, the created script doesn't behave like I expect it too and I have a to keep it separate. It seems like even in the example on Kitchen-Edition -- jquery is left out.. not sure why that was done.

**Comment by lyrixx** [comment]
Jquery is left out because many websites do the same thing. So it's pretty sure that jquery will already be in client  browser cache. ;)

**Comment by sveneisenschmidt** [comment]
So, the problem still exist?

**Comment by digitaltoad** [comment]
I've looked through Symfony and borrowed some bits to get Assetic and Twig to play nice together in Silex apps.  Let me know what you think (the code probably needs to be cleaned a bit).

https://github.com/digitaltoad/Silex-Extensions/commit/2dba9cb7c4777415b696e57e47f021103a08f4d0

**Comment by digitaltoad** [comment]
I've updated my code a bit to fix a few debug issues and pull in a bit more of the caching code provided in the AsseticBundle.

**Comment by mheap** [comment]
As far as I know, Silex + Twig + Assetic are playing together nicely now (if you use dumper->addAssets()).
